<?php
$mysqli = new mysqli("localhost", "tim5", "tim", "catfeed");
if ($mysqli->connect_errno) { // Connect_errno is a property of the mysqli object that contains the error code if the connection fails.
    die("Connection failed: " . $mysqli->connect_error);
}

// Other methods and properties of the mysqli object are:
// $mysqli->query($query) - Executes a query against the database.
// $mysqli->error - Returns the last error message from the database connection.
// $mysqli->insert_id - Returns the ID generated by the last query on a table with an AUTO_INCREMENT column.
// $mysqli->real_escape_string($string) - Escapes special characters in a string for use in an SQL statement, preventing SQL injection attacks.
// $mysqli->close() - Closes the database connection. This should be called when you're done with the database to free up resources.
